/**
 * Every metric the site shows, with the exact formula the pipeline uses.
 * Keep this in sync with vitals/metrics.py. The formulas are the source of truth; the prose explains them.
 */
export type Term = {
  slug: string;
  name: string;
  short: string; // one-sentence definition, shown in the hover card
  why: string; // why it matters, plain language
  formula: string; // the exact computation, written as text
  read: string; // how to read the number, ranges
  source: string; // the paper or convention it comes from
  caveat?: string; // where it is weak
  column: string; // column in the daily/workout tables
  hue: "strain" | "sleep" | "heart" | "oxygen" | "good" | "neutral";
  group: "Recovery" | "Sleep" | "Strain" | "Heart" | "Fitness" | "Workouts";
};

export const TERMS: Term[] = [
  {
    slug: "recovery",
    name: "Recovery",
    short: "A 0–100 score of how ready the body is for load today, built from resting heart rate, sleep, and overnight oxygen.",
    why: "It compresses three overnight signals into one number so you can decide how hard to train without reading every chart.",
    formula:
      "recovery = 0.50 × RHR component + 0.35 × sleep performance + 0.15 × SpO2 component.\nRHR component = clip(70 − 20 × z, 0, 100), where z = (today's RHR − 30-day median RHR) ÷ 30-day SD (SD floored at 1.5 bpm).\nSpO2 component maps the overnight minimum from 88% (0) to 95% (100).\nIf HRV exists the weights become HRV 40, RHR 25, sleep 25, SpO2 10.",
    read: "67 and above is green (recovered): train as planned. 34–66 is yellow (adequate): moderate load. Below 34 is red (low): rest or keep it light.",
    source: "Whoop's public description of its recovery score (RHR, HRV, respiratory rate, sleep, SpO2). The weights here are this project's own; Whoop does not publish its formula.",
    caveat: "The CMF Watch Pro 2 records no HRV, so the score leans on resting heart rate. A late meal, alcohol, or heat raises RHR and lowers the score even when you feel fine. Read it as a trend, not a verdict.",
    column: "daily.recovery",
    hue: "good",
    group: "Recovery",
  },
  {
    slug: "rhr",
    name: "Resting heart rate",
    short: "The lowest 15-minute average heart rate during last night's main sleep, in beats per minute.",
    why: "It is the most reliable everyday marker of recovery status this watch can give. A rise of 3–5 bpm above your baseline usually means fatigue, illness, dehydration, or alcohol.",
    formula:
      "Resample sleep-window HR to 5-minute means, take a rolling mean of 3 bins (15 min), and keep the minimum.\nFallbacks in order: lowest 15-minute mean of the whole day, the device's own resting HR record, the 5th percentile of the day.",
    read: "Compare against your 30-day baseline, not against other people. Lower than baseline is good. A sudden rise of more than one SD is a warning.",
    source: "Standard sports-science practice: nocturnal RHR from the lowest sustained window (e.g. Plews et al., 2013 on monitoring athletes).",
    caveat: "Needs the watch on the wrist all night with 24/7 HR enabled. Gaps in sampling can miss the true minimum and push the number up.",
    column: "daily.rhr",
    hue: "heart",
    group: "Recovery",
  },
  {
    slug: "rhr-baseline",
    name: "RHR baseline",
    short: "Your median resting heart rate over the trailing 30 days, with its standard deviation.",
    why: "A single night is noisy. The baseline is the yardstick every other heart-rate number is measured against, and it keeps one bad night from moving every zone boundary.",
    formula: "rhr_base30 = median(RHR of the previous 30 days, excluding today).\nrhr_sd30 = standard deviation of the same window.",
    read: "The shaded band on the RHR chart is baseline ± 1 SD. Nights inside the band are normal. Nights above it are the ones to notice.",
    source: "Trailing-median baselines are the common choice in HRV/RHR monitoring apps (HRV4Training, Whoop) because the median resists outliers.",
    column: "daily.rhr_base30, daily.rhr_sd30",
    hue: "heart",
    group: "Recovery",
  },
  {
    slug: "spo2",
    name: "Blood oxygen (SpO2)",
    short: "Estimated arterial oxygen saturation from the wrist sensor, in percent.",
    why: "Overnight dips can flag disturbed breathing during sleep, a chest infection, or altitude. It also feeds 15% of the recovery score.",
    formula: "Night mean and night minimum are computed over samples inside the main sleep session. Day mean covers everything else.",
    read: "95–100% is normal. Sustained readings below 92% during sleep are worth a conversation with a doctor. A single low sample is usually a bad sensor contact.",
    source: "Pulse oximetry norms (WHO). Wrist sensors are less accurate than a fingertip oximeter, especially with movement or a loose strap.",
    caveat: "The watch samples SpO2 sparsely. The night minimum is sensitive to one bad reading, which is why it only carries 15% weight.",
    column: "daily.spo2_night_mean, daily.spo2_night_min",
    hue: "oxygen",
    group: "Recovery",
  },
  {
    slug: "sleep-performance",
    name: "Sleep performance",
    short: "Hours actually asleep divided by the hours your body needed, as a percentage capped at 100.",
    why: "Raw sleep duration ignores that need changes. A hard training day or a week of short nights raises the target.",
    formula: "sleep_performance = min(100, 100 × asleep minutes ÷ sleep need minutes).",
    read: "85% and above is a full night. 70–85% is a partial night; expect a small recovery hit. Below 70% is a real deficit.",
    source: "Whoop's sleep performance definition (sleep ÷ need).",
    column: "daily.sleep_performance",
    hue: "sleep",
    group: "Sleep",
  },
  {
    slug: "sleep-need",
    name: "Sleep need",
    short: "How much sleep your body asked for last night: a base amount plus extra for yesterday's strain and for accumulated debt.",
    why: "Sleep need is personal and it moves. Training and short nights both add to it.",
    formula:
      "need = base (8.0 h) + 60 min × (yesterday's strain ÷ 21) + min(60 min, 0.5 × 7-day sleep debt).\nSleep debt = sum over the previous 7 nights of max(0, base − asleep).",
    read: "A need above 9 h means you are carrying debt or trained hard. The number is a target, not a rule.",
    source: "Modelled on Whoop's sleep need (baseline + strain + debt + naps). Base need of 8 h is a profile setting.",
    column: "daily.sleep_need_min",
    hue: "sleep",
    group: "Sleep",
  },
  {
    slug: "sleep-debt",
    name: "Sleep debt",
    short: "Hours of sleep missed against the base need over the last 7 nights.",
    why: "Debt accumulates quietly. Two hours across a week is enough to lower reaction time and raise resting heart rate.",
    formula: "debt7 = Σ over the previous 7 nights of max(0, 8.0 h − asleep). Surplus nights do not cancel debt.",
    read: "Under 2 h is fine. 2–5 h is worth an early night. Over 5 h and the recovery score will keep asking for more sleep.",
    source: "Cumulative sleep restriction studies (Van Dongen et al., 2003) show deficits compound across days.",
    column: "daily.sleep_debt7_h",
    hue: "sleep",
    group: "Sleep",
  },
  {
    slug: "sleep-stages",
    name: "Sleep stages",
    short: "Time in light, deep, and REM sleep, plus time awake, as the watch classified them from movement and heart rate.",
    why: "Deep sleep does physical repair and hormone release; REM does memory and mood. Both are cut short by late alcohol and by early alarms.",
    formula: "Stage minutes are summed from the Health Connect sleep-stage records. Asleep = light + deep + REM + unspecified sleeping.",
    read: "Typical adult split: light 50–60%, deep 13–23%, REM 20–25%. Deep is front-loaded in the night; REM is back-loaded, so a short night mostly loses REM.",
    source: "AASM sleep staging conventions. Wrist devices approximate stages; agreement with polysomnography is moderate (Cohen's κ around 0.5).",
    caveat: "Treat stage percentages as rough. Total sleep and consistency are far more reliable from a wrist than the stage split.",
    column: "daily.sleep_light_min, sleep_deep_min, sleep_rem_min, sleep_awake_min",
    hue: "sleep",
    group: "Sleep",
  },
  {
    slug: "sleep-efficiency",
    name: "Sleep efficiency",
    short: "Time asleep as a percentage of time in bed.",
    why: "Low efficiency means long time awake in bed: trouble falling asleep, or fragmented sleep.",
    formula: "efficiency = 100 × asleep minutes ÷ time-in-bed minutes.",
    read: "85% and above is normal. Below 80% suggests either lying awake or a watch that scored quiet wakefulness as sleep.",
    source: "Standard sleep-medicine definition.",
    column: "daily.sleep_efficiency",
    hue: "sleep",
    group: "Sleep",
  },
  {
    slug: "sleep-consistency",
    name: "Sleep consistency",
    short: "How regular your bedtime and wake time were over the last 7 nights, from 0 to 100.",
    why: "The circadian clock rewards regularity. Same bedtime and wake time improve sleep quality even when total hours stay the same.",
    formula:
      "sd = (circular SD of bedtime over 7 nights + circular SD of wake time over 7 nights) ÷ 2, in hours.\nconsistency = clip(100 − 25 × sd, 0, 100).\nThe circular SD treats the clock as a circle, so 23:30 and 00:30 are one hour apart, and so are 11:50 and 12:10.",
    read: "100 means bed and wake times vary by less than a few minutes. Each hour of spread costs 25 points. Below 50 is a shift-worker pattern.",
    source: "Whoop's sleep consistency metric; the social-jetlag literature (Wittmann et al., 2006).",
    column: "daily.sleep_consistency",
    hue: "sleep",
    group: "Sleep",
  },
  {
    slug: "strain",
    name: "Strain",
    short: "Total cardiovascular load for the day on a 0–21 scale that gets harder to climb the higher it goes.",
    why: "It lets a 40-minute run and a two-hour walk be compared on one scale, and it is what tomorrow's sleep need responds to.",
    formula:
      "L = Σ (minutes in zone i × i) for zones 1–5 (this is Edwards TRIMP).\nstrain = 21 × (1 − e^(−L ÷ 155)).\nOnly samples above 30% of heart-rate reserve count; sedentary time adds nothing.",
    read: "0–9 light, 10–13 moderate, 14–17 high, 18–21 all-out. About 60 minutes in zone 5 gives 18. The last three points are very hard to earn by design.",
    source: "The logarithmic shape follows Whoop's public description of strain. The constant 155 is this project's own calibration; Whoop's formula is private.",
    caveat: "Strength training and intervals produce less heart-rate load than they feel, so strain under-reads lifting sessions.",
    column: "daily.strain, workout_metrics.strain",
    hue: "strain",
    group: "Strain",
  },
  {
    slug: "trimp",
    name: "TRIMP (Banister)",
    short: "Training impulse: minutes of exercise weighted exponentially by how close the heart rate was to maximum.",
    why: "It is the standard research measure of internal training load and the input to the fitness/fatigue model.",
    formula:
      "f = (HR − RHR baseline) ÷ (HR max − RHR baseline), clipped to 0–1.\nTRIMP = Σ minutes × f × 0.64 × e^(1.92 f) (men) or 0.86 × e^(1.67 f) (women), over samples with f ≥ 0.30.",
    read: "An easy 45-minute run is roughly 50–70. A hard hour is 100–150. Weekly totals of 300–600 are a moderate recreational load.",
    source: "Banister (1991), Modeling elite athletic performance. The sex-specific weighting comes from lactate-curve fits by Morton, Fitz-Clarke and Banister (1990).",
    column: "daily.trimp",
    hue: "strain",
    group: "Strain",
  },
  {
    slug: "trimp-edwards",
    name: "TRIMP (Edwards)",
    short: "A simpler load score: minutes in each zone multiplied by the zone number, summed.",
    why: "It is the load figure that strain is built from, and it is easy to reason about by hand.",
    formula: "trimp_edwards = z1 min × 1 + z2 min × 2 + z3 min × 3 + z4 min × 4 + z5 min × 5.",
    read: "Same shape as Banister TRIMP but coarser. Use it to see which zone contributed most.",
    source: "Edwards (1993), The Heart Rate Monitor Book.",
    column: "daily.trimp_edwards",
    hue: "strain",
    group: "Strain",
  },
  {
    slug: "zones",
    name: "Heart-rate zones",
    short: "Five intensity bands defined as fractions of heart-rate reserve (the span between resting and maximum heart rate).",
    why: "Zones based on reserve adapt to your fitness: as resting HR falls, the same bpm sits in a lower zone.",
    formula:
      "reserve = HR max − RHR baseline.\nf = (HR − RHR baseline) ÷ reserve.\nz1 50–60%, z2 60–70%, z3 70–80%, z4 80–90%, z5 90–100%. Below 50% is z0 (recorded but carries no load).\nMinutes per sample = gap to the next sample, capped at 10 min in the background and 60 s inside workouts.",
    read: "z1–z2 build the aerobic base and are where most easy volume should live. z3 is tempo. z4–z5 are hard intervals; keep them to 1–2 sessions a week.",
    source: "Karvonen, Kentala and Mustala (1957) heart-rate reserve method.",
    caveat: "Zones inherit any error in HR max. If the Tanaka estimate is 10 bpm off, every boundary shifts.",
    column: "daily.z1 … z5",
    hue: "strain",
    group: "Strain",
  },
  {
    slug: "hr-max",
    name: "Heart-rate max",
    short: "The highest heart rate the model assumes you can reach, estimated from age unless you set a measured value.",
    why: "Every zone, TRIMP, strain, and the VO2max estimate depend on it.",
    formula: "HR max = 208 − 0.7 × age (Tanaka), unless hr_max is set in config.yaml.",
    read: "If a workout shows a heart rate above this value, the estimate is too low. Set the measured peak in config and recompute.",
    source: "Tanaka, Monahan and Seals (2001), meta-analysis of 351 studies. Standard error is about ±10 bpm for an individual.",
    column: "daily.hr_max_used",
    hue: "heart",
    group: "Heart",
  },
  {
    slug: "kcal-hr",
    name: "Calories from heart rate",
    short: "Energy burned during active minutes, estimated from heart rate, body weight, age, and sex.",
    why: "It is an independent check on the watch's own calorie count and it is the same formula across every workout type.",
    formula:
      "Per minute (men): (−55.0969 + 0.6309 × HR + 0.1988 × kg + 0.2017 × age) ÷ 4.184.\nSummed over samples with f ≥ 0.30, so it excludes resting metabolism.",
    read: "Compare with the device figure next to it. The device number usually includes resting burn, so it runs 1.5–2× higher across a day.",
    source: "Keytel et al. (2005), Prediction of energy expenditure from heart rate monitoring. Validated for steady aerobic work.",
    caveat: "Overstates strength sessions and understates very light activity.",
    column: "daily.kcal_hr",
    hue: "strain",
    group: "Strain",
  },
  {
    slug: "ctl",
    name: "Fitness (CTL)",
    short: "Chronic training load: a 42-day exponentially weighted average of daily TRIMP.",
    why: "It is the slow-moving component of the fitness/fatigue model. It rises with consistent training and decays over weeks when you stop.",
    formula: "CTL_today = CTL_yesterday + (TRIMP_today − CTL_yesterday) ÷ 42.",
    read: "The absolute number only means something against your own history. Aim for a gradual rise of 3–7 points a week, not jumps.",
    source: "Banister impulse-response model (1975); the CTL/ATL/TSB naming and 42/7-day constants come from Coggan's Performance Management Chart.",
    column: "daily.ctl",
    hue: "strain",
    group: "Fitness",
  },
  {
    slug: "atl",
    name: "Fatigue (ATL)",
    short: "Acute training load: a 7-day exponentially weighted average of daily TRIMP.",
    why: "It is the fast-moving component. It spikes after a hard week and falls within days of rest.",
    formula: "ATL_today = ATL_yesterday + (TRIMP_today − ATL_yesterday) ÷ 7.",
    read: "When ATL sits far above CTL you are in an overload block. That is fine for a week or two if recovery scores hold.",
    source: "Banister impulse-response model; Coggan's Performance Management Chart.",
    column: "daily.atl",
    hue: "oxygen",
    group: "Fitness",
  },
  {
    slug: "tsb",
    name: "Form (TSB)",
    short: "Training stress balance: fitness minus fatigue. Positive means fresh, negative means tired.",
    why: "It predicts how you will feel in a session. Race or test when it is slightly positive; build when it is moderately negative.",
    formula: "TSB = yesterday's CTL − yesterday's ATL.",
    read: "+5 to +25 is fresh and race-ready. −10 to −30 is a productive training state. Below −30 for more than a few days is a risk of overreaching.",
    source: "Coggan's Performance Management Chart conventions.",
    column: "daily.tsb",
    hue: "sleep",
    group: "Fitness",
  },
  {
    slug: "acwr",
    name: "Acute:chronic ratio (ACWR)",
    short: "This week's average load divided by the last four weeks' average load.",
    why: "It is the most-studied injury-risk indicator for load spikes. Big jumps in load relative to what the body is used to are what get people hurt.",
    formula: "ACWR = mean(TRIMP over 7 days) ÷ mean(TRIMP over 28 days). Needs at least 7 days of history.",
    read: "0.8–1.3 is the commonly quoted sweet spot. Above 1.5 is the danger zone. Below 0.8 means you are detraining.",
    source: "Gabbett (2016), The training-injury prevention paradox. The thresholds are debated (Impellizzeri et al., 2020), so treat them as a guide.",
    caveat: "With little training history the ratio swings wildly. Ignore it until there are 4 weeks of data.",
    column: "daily.acwr",
    hue: "strain",
    group: "Fitness",
  },
  {
    slug: "vo2max",
    name: "VO2max (estimate)",
    short: "An estimate of maximal oxygen uptake, in ml/kg/min, from the ratio of maximum to resting heart rate.",
    why: "VO2max is the single best predictor of endurance performance and of all-cause mortality. Even a rough estimate is worth tracking over months.",
    formula: "VO2max = 15.3 × HR max ÷ RHR baseline (30-day median).",
    read: "Watch the direction over months, not the value. For men in their late teens, 45–52 is average and above 55 is good.",
    source: "Uth, Sørensen, Overgaard and Pedersen (2004). Standard error about ±5 ml/kg/min.",
    caveat: "It inherits the age-based HR max, so it is a population estimate. A lab test or a hard 12-minute run test is far more accurate.",
    column: "daily.vo2max_uth",
    hue: "heart",
    group: "Fitness",
  },
  {
    slug: "hrr",
    name: "Heart-rate recovery (1 min)",
    short: "How many beats per minute your heart rate dropped in the first minute after a workout ended.",
    why: "Fast recovery reflects strong parasympathetic tone, which tracks aerobic fitness and cardiovascular health.",
    formula: "hrr_1min = mean HR over the last 15 s of the session − mean HR at 50–75 s after it.",
    read: "Above 20 bpm is good. 12–20 is average. Below 12 is poor, or the workout ended with a cool-down already done.",
    source: "Cole et al. (1999), NEJM: a drop of 12 bpm or less in the first minute predicted mortality.",
    caveat: "Needs the watch to keep sampling after the session. It is missing when sampling stops at the end.",
    column: "workout_metrics.hrr_1min",
    hue: "heart",
    group: "Workouts",
  },
  {
    slug: "hr-coverage",
    name: "Heart-rate coverage",
    short: "The share of the day for which the watch recorded heart rate.",
    why: "Every daily metric is only as good as the samples behind it. Low coverage means the watch was off or the sampling was paused.",
    formula: "coverage = 100 × minutes covered by samples (each sample covers the gap to the next, capped at 10 min) ÷ 1440.",
    read: "Above 80% is a full day. Below 50% and strain, zones, and RHR are suspect.",
    source: "Project convention.",
    column: "daily.hr_coverage_pct",
    hue: "neutral",
    group: "Heart",
  },
  {
    slug: "pct-hrmax",
    name: "Average % of HR max",
    short: "The workout's mean heart rate as a share of the assumed maximum.",
    why: "It is the quickest way to tell an easy session from a hard one without reading zones.",
    formula: "pct_hrmax_avg = 100 × mean HR ÷ HR max.",
    read: "Under 70% easy, 70–80% steady, 80–90% hard, above 90% maximal.",
    source: "ACSM intensity classification.",
    column: "workout_metrics.pct_hrmax_avg",
    hue: "heart",
    group: "Workouts",
  },
];

export const TERM_BY_SLUG: Record<string, Term> = Object.fromEntries(TERMS.map((t) => [t.slug, t]));

export const GROUPS: Term["group"][] = ["Recovery", "Sleep", "Strain", "Fitness", "Heart", "Workouts"];
